### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by wafna** [codatio/codat-docs#1006]
Hard to find descriptions of data types.  This would be especially useful for webhook consumers who don't use the APIs to fetch data.

This [page[(https://docs.codat.io/lending/data-types) looked really promising but all the links just seem to redirect to [here](https://docs.codat.io/lending-api#/), which is unhelpful.

**Comment by pzaichkina** [comment]
Hi Jason,

Sorry to hear you weren't able to find what you needed in our documentation, and thank you for your feedback. 

All of our detailed data type information is contained in each product's specific API reference in the **Schemas** section. For example, if you were looking to understand Lending's `account` data type, we recommend visiting [this dedicated page](https://docs.codat.io/lending-api#/schemas/AccountingAccount). For other data types, simply choose a different one from the Schemas list on the left. 

Please let us know if that's what you are looking for, and if not, let us know your use case - we will see how we can support you further.

Thanks, 
Polina

**Comment by pzaichkina** [comment]
Hi Jason @wafna,

We have now added data type lists to each of our products and updated the relevant links to our API reference. Hopefully, this makes it easier for you to locate and review descriptions. Let us know if you have any further feedback.

Thanks,
Polina
