### ISSUE TITLE
Plaid documentation indicates products are optional

### ISSUE THREAD

**Issue by carlpratt** [codatio/codat-docs#1011]
The section on [data mappings](https://docs.codat.io/integrations/banking/plaid/banking-plaid#data-mappings-between-plaid-and-codat) indicates that Codat data types map to specific products. However we have been informed by our implementation specialist that the types of products requested by Codat are non-configurable. When we attempted to link Plaid without having the ```Auth``` product enabled, despite not having the ```Bank Accounts``` data type enabled for sync, we received an error that the ```Auth``` product is required.

Please update the documentation to specify that the following products are **required** in order to integrate with Plaid, regardless of data types enabled: ```Auth```

**Comment by pzaichkina** [comment]
Hi @carlpratt,

Thank you for raising this issue - we have updated our Plaid documentation to reflect that all the products listed in the table are required to integrate with Plaid.

Thanks,
Polina
