### ISSUE TITLE
Unordered list Codeblock border

### ISSUE THREAD

**Issue by jmyorston** [codatio/codat-docs#322]
when a code block follows an  unordered list, it has an unusual border e.g.
![image](https://user-images.githubusercontent.com/77361832/232716387-0d389afe-62a3-44c6-80c4-8a9e5e81431d.png)
which is inconsistent with how it usually looks:
![image](https://user-images.githubusercontent.com/77361832/232716537-be46eaa1-5943-4a83-b120-684bd140b9bf.png)

**Comment by mcclowes** [comment]
Fixed, pull from main
