### ISSUE TITLE
ProcessingError thrown when syncing tables with large unit amounts

### ISSUE THREAD

**Issue by hjhdaniel** [codatio/codat-docs#454]
### Discussed in https://github.com/orgs/codatio/discussions/453

<div type='discussions-op-text'>

<sup>Originally posted by **hjhdaniel** June 12, 2023</sup>
Hi all,

Recently, I found an issue with Codat sync:
`ProcessingError` will be thrown during the syncing of data to Codat if the data contains unit numbers that are approximately `>10 billion`.

I have opened a ticket with the Codat team and they are currently working on the issue (no timeline provided for the fix yet). Would just like to open a thread here so that the issue can be updated by the Codat team here and discussed/monitored by anybody who may be affected by it.

cc: @jmyorston </div>

**Comment by johache** [comment]
+1

**Comment by wherenicc** [comment]
+1

**Comment by pj-simpson** [comment]
Tidying up this old issue and checked that the aforementioned support ticket was actioned. Fix pushed on approx 12 Jul 2023 . Closing
