### ISSUE TITLE
List bills endpoint inconsistency

### ISSUE THREAD

**Issue by Motii1** [codatio/codat-docs#637]
Hi, I am trying to fetch all bills for a given company's connection. It is written in the [docs](https://docs.codat.io/accounting-api#/operations/list-bills):

```
The List bills endpoint returns a list of bills for a given company's connection.
```

but the endpoint only wants `companyId`. There is no parameter like `connectionId` (e.g. direct costs have this parameter).

So I want to know how this endpoint works? What if a company has more than one active connection?

**Comment by pzaichkina** [comment]
Hi @Motii1,

Thank you for pointing out the inconsistency in the description, we will address this. 

The endpoint returns a list of bills for a specific company based on the `companyId` and does not consider the `connectionId` parameter. We only allow a company to link to a single accounting platform, so we don't expect you to have multiple active accounting platforms. 

If you were to unlink a company from an existing accounting platform and link it to a different one, the _List bills_ endpoint will merge the two datasets together. So if one of your customers migrated their accounting software (for example, from Xero to NetSuite), we recommend creating a new company altogether, and not just switching out the connection. This will help avoid validation errors.

This also applies to any fetch endpoints that do not have the the `connectionId` parameter.

Thanks,
Polina
