### ISSUE TITLE
Pages open centred

### ISSUE THREAD

**Issue by d-laing** [codatio/codat-docs#80]
The following docs pages open "centred" on the screen instead of being left aligned. I'm using the latest version of Chrome with zoom level set to 100%.

- [Queueing data syncs](https://codat-docs.vercel.app/using-the-api/queueing-data-syncs-1)
- [Codat APIs](https://codat-docs.vercel.app/using-the-api/overview)
- [Set up alerts](https://codat-docs.vercel.app/auth-flow/customize/set-up-webhooks)
- [Optimize your auth flow](https://codat-docs.vercel.app/auth-flow/optimize/optimize-the-connection-journey)
- [Expense transactions](https://codat-docs.vercel.app/sync-for-expenses/sync-process/expense-transactions)
- [Initiating a sync](https://codat-docs.vercel.app/sfc/sync-for-commerce-knowledge-base/initiating-a-sync)
- [Enable access to additional banking data](https://codat-docs.vercel.app/integrations/banking/proxy-access-banking-data/enabling-proxy-access)

And possibly a few more.

**Comment by d-laing** [comment]
_Observed incorrect alignment:_

![optimize-auth-flow-centred](https://user-images.githubusercontent.com/20324857/218801090-6ccb6f6c-3484-4643-ba5d-b650a08770b4.jpg)
![queue-data-syncs-centred](https://user-images.githubusercontent.com/20324857/218801135-558706f3-d164-4f04-9aa6-4ff8b12f6409.jpg)

_Observed correct alignment:_

![querying-n-left-aligned-correct](https://user-images.githubusercontent.com/20324857/218801157-3ff9414b-7278-4dbb-8bf7-2b2825920db4.jpg)

**Comment by mcclowes** [comment]
Will think about this later
