### ISSUE TITLE
Line spacing in first paragraphs with links

### ISSUE THREAD

**Issue by d-laing** [codatio/codat-docs#91]
I noticed the line spacing is compressed on some of the pages. It seems to be related to there being a link `<a href>` somewhere in the first line.

Line spacing elsewhere looks very good.

Example, Square:

![codat-new-docs-line-spacing](https://user-images.githubusercontent.com/20324857/219078541-453edbf5-c2fe-49c7-820a-ce78123dce41.jpg)

**Comment by mcclowes** [comment]
💯

**Comment by d-laing** [comment]
Sounds good. Does this issue only affect the first paragraph on a page?

**Comment by d-laing** [comment]
Thanks. For ease of maintenance, I think the first option is preferable. The user can decide whether to open the link in a new tab or not.
